### ISSUE TITLE
Saving file causes [TypeError: Cannot read property 'apply' of null]

### ISSUE THREAD

**Issue by newmana** [hoovercj/vscode-ghc-mod#13]
0.2.2 of the extension installed as well as ghc-mod version 5.5.0.0 compiled by GHC 7.10.3.

**Comment by hoovercj** [comment]
Can you give me more information?

I haven't seen this error. Do you have a set of steps to consistently reproduce this issue?

**Comment by newmana** [comment]
All I can see is the output of the console.

Is there a debug mode or something to see what commands are failing?

**Comment by hoovercj** [comment]
You can set "Haskell.ghcMod.logLevel": " log" to get the most verbose output.

Also, does this happen for every file? Or just certain ones?

And are you on Windows, Linux, osx?

**Comment by newmana** [comment]
Each time I hit save I get the error message out twice:
[TypeError: Cannot read property 'apply' of null]
[TypeError: Cannot read property 'apply' of null]

Same behaviour on OSX or Windows.  It happens in Turtle scripts or normal project files.

My settings are (on OSX):
// Place your settings in this file to overwrite the default settings
{
   "haskell.ghcMod.executablePath": "/Users/blah/.local/bin/ghc-mod",
   "haskell.ghcMod.logLevel": "log"
}

Windows:
// Place your settings in this file to overwrite the default settings
{
    "haskell.ghcMod.executablePath": "C:/Users/blah/AppData/Roaming/local/bin/ghc-mod.exe",
    "haskell.ghcMod.logLevel": "log"
}

ghc-mod --version gives:
ghc-mod version 5.4.0.0 compiled by GHC 7.10.2

**Comment by hoovercj** [comment]
I should have mentioned: the log output shows up in the chrome dev tools within the window. If you open the vs code command palette and type "developer tools" it should give an option to open that. Then the logging shows up in the console.

Another backlog item is seeing is output channels are available to language services to make them easier to find and read.

**Comment by newmana** [comment]
Thanks and maybe success then - I think the error is:
[Extension Host] ghc-mod stderr: <command line>: cannot satisfy -package-id base-4.8.2.0-bfcc6de9ee2962ae54db40ece3022dc5
    (use -v for more information)

With a quick search points to:
https://github.com/DanielG/ghc-mod/issues/607

So looks like a problem with ghc-mod.

Not sure how to fix it.

**Comment by hoovercj** [comment]
Cool, hopefully you can get it solved.

**Comment by newmana** [comment]
This is apparently a classic ghc-mod error - the version of GHC for the project (defined in stack.yaml) vs the version of GHC for the global.  Make sure version agree and it works!

**Comment by hoovercj** [comment]
Glad you got it sorted out. So you just added the oath to the local ghc-mod in workspace settings and it worked?

**Comment by newmana** [comment]
Yeah.  The User settings now looks like:
{
    "haskell.ghcMod.executablePath": "/home/andrew/.local/bin/ghc-mod",
    "haskell.hlint.executablePath": "/home/andrew/.local/bin/hlint",
    "stylishHaskell.commandLine": "/home/andrew/.local/bin/stylish-haskell"
}
