### ISSUE TITLE
'-' in comments causes error

### ISSUE THREAD

**Issue by ImsungChoi** [hoovercj/vscode-ghc-mod#15]
When I locate my cursor on '--------' in comments, it causes the following errors.

Error running ghc-mod command -ghc-mod crashed on command info 
ghc-mod crashed on command info

**Comment by hoovercj** [comment]
Thanks, I just published a fix to the marketplace (v0.2.5)

**Comment by ImsungChoi** [comment]
Thanks hoover!!!
