### ISSUE TITLE
Getting this issue "Couldn't start ghc-mod process Error: Command failed: ghc-mod version"

### ISSUE THREAD

**Issue by rokfrog** [hoovercj/vscode-ghc-mod#18]
I got VScode installed in my Ubuntu 14.04 machine . Haskell installed using Stackage.

**Error: Couldn't start ghc-mod process Error: Command failed: ghc-mod version`**

Error even reported in Stackoverflow:
https://stackoverflow.com/questions/38322699/vscode-editor-got-errors-while-using-haskell-installed-using-stackage

**Comment by hoovercj** [comment]
It looks like you've installed 2 extensions for vscode, one for linting and one for running ghc-mod, but you don't have hlint or ghc-mod installed.

If you are using [this ghc-mod extension](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-ghc-mod), make sure you have ghc-mod installed through cabal or through stack.

If you are using [this linter extension](https://marketplace.visualstudio.com/items?itemName=hoovercj.haskell-linter), make sure you have hlint installed through cabal or through stack.

To install with cabal, run:
`cabal install hlint`
and
`cabal install ghc-mod`

To install via stack, see the stack documentation.
