### ISSUE TITLE
Issues from B show up in A if A depends on B

### ISSUE THREAD

**Issue by hoovercj** [hoovercj/vscode-ghc-mod#2]
ghc-mod reports issues for a file and all dependencies. So if file A depends on B and B has an issue, doing a check on A will show the issues from B.

The way this is handled currently means that the issues from B will show up in A.

**Comment by hoovercj** [comment]
VS Code gives the URI: file:///path/to/file.hs
ghc-mod output gives the URI: file:\path\to\file.hs

**Comment by danstiner** [comment]
Attached simple repro case

Note the error about module name not matching is from file A because it has no module declaration, but it is reported by this plugin when looking at file B

[repro-cross-module-ghc-mod-warnings.zip](https://github.com/hoovercj/vscode-ghc-mod/files/74156/repro-cross-module-ghc-mod-warnings.zip)

**Comment by danstiner** [comment]
Another example using compile-able files and real warnings.

λ ghc-mod check A.hs
A.hs:3:1:Warning: Top-level binding with no type signature: one :: Integer

λ ghc-mod check B.hs
A.hs:3:1:Warning: Top-level binding with no type signature: one :: Integer
B.hs:8:1:Warning: Defined but not used: `two'

When looking at file B.hs, this plugin displays the warning from file A on line 3 of file B,

[repro-cross-module-ghc-mod-warnings-2.zip](https://github.com/hoovercj/vscode-ghc-mod/files/74172/repro-cross-module-ghc-mod-warnings-2.zip)

**Comment by hoovercj** [comment]
@danstiner please confirm that commit 2422bef on the diagnostics-fix branch fixes this issue.

**Comment by danstiner** [comment]
Confirm it seems to be fixed, awesome!

**Comment by hoovercj** [comment]
Thanks!
