### ISSUE TITLE
Spaces in paths problematic in version 0.3.1?

### ISSUE THREAD

**Issue by mpilgrem** [hoovercj/vscode-ghc-mod#21]
EDITED: Since my original comment below, VS Code has updated to version 1.4.0 and I can no longer reproduce the problem - so perhaps it was never a problem.

> Experimenting with paths to the Haskell code file that include or exclude spaces, on Windows 10, the extension seems to work fine with no spaces in the path but not work if there is a space (all else equal).

**Comment by hoovercj** [comment]
Thanks for reporting. I'll close it for now, but please reopen if it happens again and I'll see if I can dig into it.
