### ISSUE TITLE
Error when trying to develop

### ISSUE THREAD

**Issue by archaeron** [hoovercj/vscode-ghc-mod#30]
I have two issues when I try to develop locally.

One is this `npm` command here.
https://github.com/hoovercj/vscode-ghc-mod/blob/master/client/.vscode/launch.json#L14
https://github.com/hoovercj/vscode-ghc-mod/blob/master/client/.vscode/launch.json#L25
I always get errors when I don't delete them. Just calling npm doesn't do anything anyways.

The other issue is the same that travis has:
https://travis-ci.org/hoovercj/vscode-ghc-mod/jobs/159156046

```
npm ERR! Error extracting /Users/travis/.npm/vscode-languageclient/2.4.1/package.tgz archive: ENOENT: no such file or directory, open '/Users/travis/.npm/vscode-languageclient/2.4.1/package.tgz'
```

i can fix this by updating the language client here: https://travis-ci.org/hoovercj/vscode-ghc-mod/jobs/159156046
to `2.4.2-next.24`

**Comment by archaeron** [comment]
I can fix these issues in a PR if you'd like.
I just wasn't sure if there are reasons for mboth things :)

**Comment by hoovercj** [comment]
I need to see why the prelaunch task was there in the first place. I certainly didn't add it manually, so it must have been auto-generated, part of the yeoman generator for code extensions, or something similar. That said, it does look like it needs removed.

It doesn't seem like building against a vNext package is the right solution. I'll have to look into this a bit

**Comment by hoovercj** [comment]
Update on your first issue: `"preLaunchTask": "npm"` IS necessary. It isn't simply calling `npm`, it is calling the `npm` task from `tasks.json`, which is the task that makes sure the extension is compiled before launching it.

This is included in the official yeoman generator for code and in their extension samples. I agree that it could be better named/more intuitive, but I won't be changing it. It is briefly explained at this [link](https://code.visualstudio.com/docs/extensions/debugging-extensions).

You might also check out a relevant issue in the vscode repo: https://github.com/Microsoft/vscode/issues/8493

**Comment by archaeron** [comment]
in the npm issue you linked it says:

> Thanks for creating great repro steps!
> The issue is that you have build errors in your project, if you open the problems panel you can see a bunch of them.

Could that be it?

**Comment by hoovercj** [comment]
I don't have any build errors in mine, I don't have any issue building, launching, debugging, etc. Are you seeing some in yours?

**Comment by hoovercj** [comment]
I'm closing this for now, but if you still think there is something that can only be fixed with a change to the project, please re-open
