### ISSUE TITLE
Marketplace review - Extension not working

### ISSUE THREAD

**Issue by hoovercj** [hoovercj/vscode-ghc-mod#38]
Rayner Pupo:
"I can't make it work, I've installed vscode and the ghc-mod addon, restarted the app and none of the features are working so far. I've opened the Developers console and there isn't any error or warning."

**Comment by hoovercj** [comment]
Troubleshooting steps:
- Have you installed everything needed for the extension to run?
- [X] Vscode
- [X] Vscode ghc-mod extension
- [ ] ghc-mod itself? (either via `caball install ghc-mod`, stack, or a different method: http://www.mew.org/~kazu/proj/ghc-mod/en/install.html)
- Add this to your user or workspace settings to enable the most verbose logging: `"haskell.ghcMod.logLevel": "log"`
- What VS Code version, ghc-mod version, and OS version are you using? For example:
  `code -v` -> 1.6.1
  `ghc-mod --version` -> ghc-mod version 5.5.0.0 compiled by GHC 7.10.3

**Comment by dpwiz** [comment]
I may have the same problem in vs code 1.7.2 and ghc-mod version 5.6.0.0 compiled by GHC 8.0.1

I've set `logLevel` to `log`. There is only a stack trace in extension console:

```
TypeError: Cannot read property 'apply' of null
    at CallbackList.invoke (/home/wiz/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:103:38)
    at Emitter.fire (/home/wiz/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at /home/wiz/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/lib/main.js:287:39
    at handleNotification (/home/wiz/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:267:17)
    at process.callback (/home/wiz/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:363:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by hoovercj** [comment]
Hi @wiz, I'm sorry you're having this problem.

This looks similar to the stack trace reported here: https://github.com/hoovercj/vscode-ghc-mod/issues/39

After looking at the logs in the developer tools, that user found that the solution in that case was to run `cabal install`.

Please let me know if that helps. I now see that changing over to properly use output channels for logging needs to move up on my priority list.

**Comment by dpwiz** [comment]
I invoked `ghc-mod` manually and it indeed shows the symbol information requested.

I've tried to set `executablePath` to stack wrapper (I don't use cabal) and nothing changed.

**Comment by hoovercj** [comment]
Hm. You can open the developer tools (in the command palette" "toggle developer tools") and you should see more useful logs there from the extension. Does that show anything useful?

**Comment by dpwiz** [comment]
Welp.. It actually works now. Damn heisenbugs :smile: 

So, my config is

```
"haskell.ghcMod.executablePath": "/home/wiz/.local/bin/stack-ghcmod",
```

Which points to an script containing simply

```bash
stack exec ghc-mod -- $@
```

**Comment by hoovercj** [comment]
My stack support needs improved, but I'm glad that it's working for you for now. If you have the same problem again and can get more information from the developer tools, please paste it here and reopen the issue.

Thanks for your patience and I hope you find the extension useful!

**Comment by hoovercj** [comment]
@wiz I'm glad you were able to workaround my lack of stack support, but you might find that it has improved. The setting `haskell.ghcMod.executablePath": "stack"` should help you avoid needing a bash script for indirection.

**Comment by dpwiz** [comment]
Thanks! I'll sure check it out.
