### ISSUE TITLE
Hovering a negative numeric literal crashes ghc-mod

### ISSUE THREAD

**Issue by rotemdan** [hoovercj/vscode-ghc-mod#41]
In:
```hs
main :: IO ()
main = print (test 1)

test :: Int -> Int
test x = x + (-1)
```
Hovering over `-1` causes the error "ghc-mod crashed". The Developer console shows:
```
Error running ghc-mod command -ghc-mod crashed on command info test.hs -1)
 with savedLines NG Invalid option `-1)'\n\nUsage:  info FILE SYMBOL\n  Look up an identifier in the context of FILE (like ghci's `:info')
```

My guess is that ghc-mod it parses the `-` as a command line switch instead of part of a value. Perhaps there's some sort of escaping or quoting that could be applied?

I'm using GHC 8.0.1 (full bundle) on Windows 10 x64.

(I'm sorry but I'm very new to Haskell/GHC so there isn't much I can tell further. )

**Comment by KillyMXI** [comment]
Same here.
Crashing on -1, -n, etc.

**Comment by KillyMXI** [comment]
It is not a command line parsing issue. It is source code parsing issue.
Relevant file: [/server/src/utils/document.ts](https://github.com/hoovercj/vscode-ghc-mod/blob/master/server/src/utils/document.ts)
DocumentUtils.getWordAtPosition() returns minus sign with whatever attached to it. Here is an example how it breaks:
```
> '(-1)'.replace(/[(),]/, '')
< "-1)"
```
As a workaround, for now, you can put a space between minus sign and digit.
Ghc-mod will work happily and return info on binary operator (-), which is not quite what it is in this case, but it can't be helped, I guess.

As a solution for the issue, either getWordAtPosition() should be improved, or this case should be taken into account in [/server/src/ghcModProviders/ghcModProvider.ts](https://github.com/hoovercj/vscode-ghc-mod/blob/master/server/src/ghcModProviders/ghcModProvider.ts) (functions getInfoHelper() and isBlacklisted()) somehow. Most likely both.
It, probably, can be solved with textmate, along with and as mentioned in #31.

Related issue: in case of `square x = x*x` it won't be able to show info on (*) operator.

**Comment by danstiner** [comment]
@KillyMXI You've hit the nail on the head, ```ghc-mod info``` expects a valid symbol name to look up, and while the heuristics in getWordAtPosition and isBlacklisted work most of the time they fail in these edge cases and pass in invalid things like "-1)" or "x*x".

This is inevitably going to be tricky, we are trying to take a character position and expand it to be the entire symbol without doing a full parse of the file to get semantic info. Based on looking at the Haskell language definition (https://www.haskell.org/onlinereport/lexemes.html) I think we are only worried about being able to get info on identifiers (varid and conid) and operators (varsym and consym). These have non-overlapping sets of valid characters (letters vs punctuation basically), so it should be possible to tell from looking at the initial character whether it is an identifier or a operator and then expand appropriately to the entire symbol.

I have an initial implementation done and it seems to work perfectly, I'll try to come back to it in the next couple of days and get it merge worthy (needs cleanup, unicode support, and better bounds checking): https://github.com/danstiner/vscode-ghc-mod/blob/issue41/server/src/utils/document.ts

**Comment by hoovercj** [comment]
Big thanks to @danstiner for putting a fix together for this.
