### ISSUE TITLE
Extension does not contribute haskell language

### ISSUE THREAD

**Issue by hoovercj** [hoovercj/vscode-ghc-mod#43]
via @Reiniert - https://github.com/hoovercj/vscode-ghc-mod/issues/35#issuecomment-272495371
> My fresh, basic install of VS Code in combination with stack ghc-mod and your plugin version 1.0.1 does not seem to work. When opening a .hs file, language mode 'Plain Text' is detected. Haskell does not show up as an option when changing the Language Mode. No syntax high-lighting or any other language-related features are visible.
> What I tried so far:
> 
> Modified the user settings to use "haskell.ghcMod.logLevel": "log". No output was visible in the DevTools console.
> Modified the user setting for "haskell.ghcMod.executablePath" in all kinds of ways, with no visible effect.
> Started VS Code via stack exec code, no difference visible.
> Versions:
> 
> code -v -> 1.8.1
> ghc-mod --version -> ghc-mod version 5.6.0.0 compiled by GHC 8.0.1
> platform: Windows 7, 32 bits

**Comment by hoovercj** [comment]
This is semi by-design.

This [extension](https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell) provides the syntax highlighting and contributes the language, so I didn't contribute the language in my extension. ["Contributing a language" is something extensions specify in their manifest to tell vs code what file extensions belong to a language, give it a name, etc.].

That said, it wouldn't hurt to add this.

**Comment by nicolasg-da** [comment]
@hoovercj I think you can add "modules you recommend to install with yours" somehow.

**Comment by reiniert** [comment]
After adding the recommended extension and following the suggestion concerning hasktags as well everything looks and behaves much better. Thanks for creating this.

**Comment by hoovercj** [comment]
Glad it is working for you, @reiniert! If you have any other issues, please create a new issue so I can track it. Happy coding :-)

**Comment by hoovercj** [comment]
@nicolasg-da there are multiple ways to go about it.

1. Simply "contribute" the language so it is activated and shows up in the list, but without highlighting
2. Use the `extensionDependencies` section of the manifest to declare a dependency on the haskell syntax highlighting extension and ensure that it is installed when my extension is installed.

I will likely go with option 2

**Comment by nicolasg-da** [comment]
@hoovercj I think option 2 is a good choice :) Thanks for all of this!

**Comment by hoovercj** [comment]
Solved in #46 by making the syntax highlighting extension a dependency.
