### ISSUE TITLE
Pragmas are not filtered, crashing ghc-mod on hover.

### ISSUE THREAD

**Issue by KillyMXI** [hoovercj/vscode-ghc-mod#48]
Hovering opening part of pragma like this: `{-# LANGUAGE NoMonomorphismRestriction #-}`
results in error message `ghc-mod crashed on command info hello.hs -#`
Nested comments check in /server/src/utils/document.ts should be extended to include this case.

**Comment by hoovercj** [comment]
Thanks for the report!

@danstiner: I think `ghcModProvider.isBlacklisted` needs moved into `document.ts` and then after your regex to find the current symbol, we return `isBlacklisted(symbol) ? '' : symbol`

Did your see some easy to regex definitions of comments and pragma boundaries when you read the grammar spec?

**Comment by danstiner** [comment]
Ha, I was just thinking pragmas might not be handled well, good find.

@hoovercj, that's a good idea, I'll look at it tonight.

**Comment by danstiner** [comment]
Did not move isBlackedlisted, technically "->" is a valid operator symbol, it's just a special reserved one that it does not make sense to lookup info on hence being disallowed. While the logic in getSymbolAtOffset is actually filtering out entirely non-valid symbols. Some better naming could probably solve this and allow the isBlackelisted to be moved, I just got lazy :)
