### ISSUE TITLE
Crash spam

### ISSUE THREAD

**Issue by HuwCampbell** [hoovercj/vscode-ghc-mod#51]
When the plugin or ghc-mod isn't working properly, I get dozens of error message toasts, with new ones appearing every second. This happens all the time if one is sandboxing, changing their cabal file, or utilising multiple versions of ghc.

It's very annoying.

If ghc-mod is crashing, I would prefer a status bar indicator instead of a ton of toasts.

**Comment by hoovercj** [comment]
Thanks for the feedback.

As a temporary workaround, you can add `"haskell.ghcMod.logLevel": "none"` to your settings.

I'll look into moving non-actionable errors to the status bar.

**Comment by HuwCampbell** [comment]
Thanks for the tip. Despite some niggles, I think it's a great plugin.

**Comment by hoovercj** [comment]
Thanks for the feedback and the kind words. This is fixed and published with v1.1.1
